
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = '}\x19\xe6\xae\xf7D\xc6O-o,\x89\x18\xb0\xe6\x0c'

_lr_action_items = {'RPAREN':([9,17,14,18,8,16,19,1,20,2,],[-10,-3,-7,-6,16,-8,-4,-10,-5,-9,]),'NAME':([11,4,10,12,7,0,13,6,],[9,9,9,9,9,1,9,9,]),'NUMBER':([12,4,11,10,7,6,13,0,],[2,2,2,2,2,2,2,2,]),'TIMES':([18,1,19,16,15,8,2,20,17,9,5,14,],[-6,-10,13,-8,13,13,-9,-5,13,-10,13,-7,]),'EQUALS':([1,],[7,]),'PLUS':([14,9,15,17,1,8,5,16,19,20,2,18,],[-7,-10,10,-3,-10,10,10,-8,-4,-5,-9,-6,]),'LPAREN':([12,13,11,6,10,7,4,0,],[4,4,4,4,4,4,4,4,]),'$':([20,2,5,14,18,19,1,3,9,17,16,15,],[-5,-9,-2,-7,-6,-4,-10,0,-10,-3,-8,-1,]),'MINUS':([19,15,9,6,16,13,12,10,2,8,17,5,14,4,11,20,1,7,0,18,],[-4,12,-10,6,-8,6,6,6,-9,12,-3,12,-7,6,6,-5,-10,6,6,-6,]),'DIVIDE':([20,2,17,9,5,14,16,19,15,8,18,1,],[-5,-9,11,-10,11,-7,-8,11,11,11,-6,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'expression':([4,6,11,13,7,12,10,0,],[8,14,18,20,15,19,17,5,]),'statement':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('statement',3,'p_statement_assign','calc.py',60),
  ('statement',1,'p_statement_expr','calc.py',64),
  ('expression',3,'p_expression_binop','calc.py',68),
  ('expression',3,'p_expression_binop','calc.py',69),
  ('expression',3,'p_expression_binop','calc.py',70),
  ('expression',3,'p_expression_binop','calc.py',71),
  ('expression',2,'p_expression_uminus','calc.py',78),
  ('expression',3,'p_expression_group','calc.py',82),
  ('expression',1,'p_expression_number','calc.py',86),
  ('expression',1,'p_expression_name','calc.py',90),
]
